name: Build feat20

on:
  push:
    branches: [ "feat20" ]
  pull_request:
    branches: [ "feat20" ]

env:
  # path + common prefix
  EXPECTED_WARNINGS: .github\workflows\ExpectedWarnings\WarningList
  
  # expecting windows paths
  REDACT_LOCATIONS: >
    %{ $_ -replace '(?<=\.[hc]pp)\(\d+,\d+\):',':' -replace '[A-Za-z]:\\(\w+\\)*EnumerablesCpp\\','EnumerablesCpp\' }

  # some versions use guids or ordinal numbers
  REDACT_LAMBDAS: >
    %{ $_ -replace '<lambda_[a-fA-F\d]+>','<lambda_###>' }

permissions:
  contents: read

jobs:
  clangBuild:
    name: Build on Clang
    runs-on: windows-latest
    timeout-minutes: 4

    strategy: &matrixStrategy
      max-parallel: 2
      matrix:
        config: [Debug, Release]
        platform:
        - sln: x64
          proj: x64
        - sln: x86
          proj: Win32

    env:
      # ideally, config should be irrelevant
      WARNINGS_LOG: Warnings_Clang_${{matrix.platform.proj}}_${{matrix.config}}.txt
      WARNINGS_REFERENCE: Clang_${{matrix.platform.proj}}.txt

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: >
        msbuild /M /P:Platform=${{matrix.platform.sln}},Configuration=${{matrix.config}}
        /FileLogger /FLP:"logfile=$env:WARNINGS_LOG;verbosity=Quiet"
        EnumerablesCpp.sln /t:TestsClang

    - &warnCheck
        name: Check warnings
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          $act = type $env:WARNINGS_LOG | ${{env.REDACT_LOCATIONS}} | ${{env.REDACT_LAMBDAS}}
          $exp = type ${{env.EXPECTED_WARNINGS}}_${{env.WARNINGS_REFERENCE}}
          compare $act $exp | tee -variable diff
          if ($diff) {
              echo "`n ---- Actual WarningList ----"
              echo $act
              exit 1
          } else {
              echo 'All warnings were expected.'
          }

    - name: Run tests
      run: ${{matrix.platform.proj}}\${{matrix.config}}\TestsClang\TestsClang.exe -N -Q
      working-directory: ${{env.GITHUB_WORKSPACE}}


  msvcBuild:
    name: Build on MSVC
    runs-on: windows-latest
    timeout-minutes: 4
    
    strategy: *matrixStrategy

    env:
      # ideally, config should be irrelevant
      WARNINGS_LOG: Warnings_MSVC_${{matrix.platform.proj}}_${{matrix.config}}.txt
      WARNINGS_REFERENCE: MSVC_${{matrix.platform.proj}}.txt

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: >
        msbuild /M /P:Platform=${{matrix.platform.sln}},Configuration=${{matrix.config}}
        /FileLogger /FLP:"logfile=$env:WARNINGS_LOG;verbosity=Quiet"
        EnumerablesCpp.sln /t:TestsMSVC

    - *warnCheck

    - name: Run tests
      run: ${{matrix.platform.proj}}\${{matrix.config}}\TestsMSVC\TestsMSVC.exe -N -Q
      working-directory: ${{env.GITHUB_WORKSPACE}}

