name: Build master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIG: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  clangBuild:
    name: Build on Clang
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIG}};Platform=${{env.BUILD_PLATFORM}} TestsClang\TestsClang.vcxproj
   
  msBuild:
    name: Build on MSVC
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # NOTE: only the latest toolset is available -> override project setting!
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIG}};Platform=${{env.BUILD_PLATFORM}};PlatformToolset=v143 TestsMSVC\TestsMSVC.vcxproj
