name: Build master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # path + common prefix
  EXPECTED_WARNINGS: .github\workflows\ExpectedWarnings\WarningList
  
  # expecting windows paths
  REDACT_LOCATIONS: >
    %{ $_ -replace '(?<=\.[hc]pp)\(\d+,\d+\):',':' -replace '[A-Za-z]:\\(\w+\\)*EnumerablesCpp\\','EnumerablesCpp\' }

  # some versions use guids or ordinal numbers
  REDACT_LAMBDAS: >
    %{ $_ -replace '<lambda_[a-fA-F\d]+>','<lambda_###>' }

permissions:
  contents: read

jobs:
  clangBuild:
    name: Build on Clang
    runs-on: windows-latest
    timeout-minutes: 4

    strategy: &matrixStrategy
      max-parallel: 2
      matrix:
        platform: [x64, Win32]
        config: [Debug, Release]
        testResultsView: [null]   # default set by Tests/Enumerables.cpp
        include:
        - platform: x64
          config: Debug
          testResultsView: "2"    # evaluate all on creation - compiles an extra code path,
                                  # while cancels forcing the emission of Test/Print functions
        - platform: x64
          config: Release
          testResultsView: "2"

    env:
      # ideally, config and ResultsView level should be irrelevant
      WARNINGS_LOG: Warnings_Clang_${{matrix.platform}}_${{matrix.config}}${{matrix.testResultsView}}.txt
      WARNINGS_REFERENCE: Clang_${{matrix.platform}}.txt
      EXTRA_PROPS: &extraProperties >-
        ${{matrix.testResultsView && ',TestResultsView=' || ''}}${{matrix.testResultsView}}

    steps:
    - uses: actions/checkout@v5

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: >
        msbuild /M /P:Platform=${{matrix.platform}},Configuration=${{matrix.config}}${{env.EXTRA_PROPS}}
        /FileLogger /FLP:"logfile=$env:WARNINGS_LOG;verbosity=Quiet"
        TestsClang\TestsClang.vcxproj

    - &warnCheck
        name: Check warnings
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          $act = type $env:WARNINGS_LOG | ${{env.REDACT_LOCATIONS}} | ${{env.REDACT_LAMBDAS}}
          $exp = type ${{env.EXPECTED_WARNINGS}}_${{env.WARNINGS_REFERENCE}}
          compare $act $exp | tee -variable diff
          if ($diff) {
              echo "`n ---- Actual WarningList ----"
              echo $act
              exit 1
          } else {
              echo 'All warnings were expected.'
          }

    - name: Run tests
      run: TestsClang\${{matrix.platform}}\${{matrix.config}}\TestsClang\TestsClang.exe -N -Q
      working-directory: ${{env.GITHUB_WORKSPACE}}


  msvcBuild:
    name: Build on MSVC
    runs-on: windows-2022
    timeout-minutes: 4
    
    strategy: *matrixStrategy

    env:
      # ideally, config should be irrelevant
      WARNINGS_LOG: Warnings_MSVC_${{matrix.platform}}_${{matrix.config}}${{matrix.testResultsView}}.txt
      WARNINGS_REFERENCE: MSVC_${{matrix.platform}}.txt
      EXTRA_PROPS: *extraProperties

    steps:
    - uses: actions/checkout@v5

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # only later toolsets are available -> override project setting!
      run: >
        msbuild /M /P:Platform=${{matrix.platform}},Configuration=${{matrix.config}}${{env.EXTRA_PROPS}},PlatformToolset=v142
        /FileLogger /FLP:"logfile=$env:WARNINGS_LOG;verbosity=Quiet"
        TestsMSVC\TestsMSVC.vcxproj

    - *warnCheck

    - name: Run tests
      run: TestsMSVC\${{matrix.platform}}\${{matrix.config}}\TestsMSVC\TestsMSVC.exe -N -Q
      working-directory: ${{env.GITHUB_WORKSPACE}}

