name: Build master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIG: Release
  BUILD_PLATFORM: x64

  # path + common prefix
  EXPECTED_WARNINGS: .github\workflows\ExpectedWarnings\WarningList
  
  # expecting windows paths
  REDACT_LOCATIONS: -replace '(?<=\.[hc]pp)\(\d+,\d+\):',':' -replace '[A-Za-z]:\\(\w+\\)*EnumerablesCpp\\','EnumerablesCpp\'

permissions:
  contents: read

jobs:
  clangBuild:
    name: Build on Clang
    runs-on: windows-latest

    env:
      # ideally, configuration should be irrelevant
      # TODO: BUILD_PLATFORM
      LOGS_SUFFIX: Clang_x64.txt

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: >
        msbuild /M /P:Platform=${{env.BUILD_PLATFORM}},Configuration=${{env.BUILD_CONFIG}}
        /FileLogger /FLP:'logfile=Warnings_${{env.LOGS_SUFFIX}};verbosity=Quiet'
        TestsClang\TestsClang.vcxproj

    - name: Check warnings
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $act = type 'Warnings_${{env.LOGS_SUFFIX}}' | %{ $_ ${{env.REDACT_LOCATIONS}} }
        $exp = type ${{env.EXPECTED_WARNINGS}}_${{env.LOGS_SUFFIX}}
        compare $act $exp | tee -variable diff
        if ($diff) {
            echo "`n ---- Actual WarningList ----"
            echo $act
            return 1
        }


  msvcBuild:
    name: Build on MSVC
    runs-on: windows-latest
    
    #temp saving
    needs: clangBuild

    env:
      # ideally, configuration should be irrelevant
      # TODO: BUILD_PLATFORM
      LOGS_SUFFIX: MSVC_x64.txt

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # only the latest toolset is available -> override project setting!
      run: >
        msbuild /M /P:Platform=${{env.BUILD_PLATFORM}},Configuration=${{env.BUILD_CONFIG}},PlatformToolset=v143
        /FileLogger /FLP:'logfile=Warnings_${{env.LOGS_SUFFIX}};verbosity=Quiet'
        TestsMSVC\TestsMSVC.vcxproj

    - name: Check warnings
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $act = type 'Warnings_${{env.LOGS_SUFFIX}}' | %{ $_ ${{env.REDACT_LOCATIONS}} }
        $exp = type ${{env.EXPECTED_WARNINGS}}_${{env.LOGS_SUFFIX}}
        compare $act $exp | tee -variable diff
        if ($diff) {
            echo "`n ---- Actual WarningList ----"
            echo $act
            return 1
        }
